esphome:
  name: ac-downstairs
  friendly_name: Downstairs AC

substitutions:
  name: ac-downstairs
  friendly_name: Downstairs AC
  remote_temp_sensor: sensor.thermometer_living_room_temperature

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: esp-idf

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO16
  rx_pin: GPIO18

# Enable Home Assistant API
api:
  encryption:
    key: <redacted>
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
        - lambda: 'id(hp).set_remote_temperature((temperature - 32.0) * (5.0 / 9.0));'
    - service: use_internal_temperature
      then:
        - lambda: "id(hp).set_remote_temperature(0);"

ota:
  - platform: esphome
    password: <redacted>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.101.54
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.101.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Downstairs-Heat-Pump"
    password: <redacted>
    manual_ip:
      static_ip: 192.168.1.1
      gateway: 192.168.1.1
      subnet: 255.255.255.0

packages:   # as a list
  - !include ac.yaml
