esphome:
  name: ac-upstairs
  friendly_name: Upstairs AC

substitutions:
  name: ac-upstairs
  friendly_name: Upstairs AC
  remote_temp_sensor: sensor.thermometer_upstairs_temperature

esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  framework:
    type: esp-idf

uart:
  id: HP_UART
  baud_rate: 2400
  tx_pin: GPIO16
  rx_pin: GPIO18

# Enable Home Assistant API
api:
  encryption:
    key: <redacted>
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: <redacted>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.101.53
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.101.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  reboot_timeout: 0s

packages:   # as a list
  - !include ac.yaml
